// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-UiLowxnRMnKC3IJ6Qxw61i_HsFDhpOg',
    appId: '1:704952785545:web:3ff3e3cfab8dd4dcdcc458',
    messagingSenderId: '704952785545',
    projectId: 'parcialjuego',
    authDomain: 'parcialjuego.firebaseapp.com',
    storageBucket: 'parcialjuego.firebasestorage.app',
    measurementId: 'G-BJCLR6BC8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1iMLR7tN_-XzvRrHK-db0z7Lcah88Ykk',
    appId: '1:704952785545:android:aae355f6ddda8810dcc458',
    messagingSenderId: '704952785545',
    projectId: 'parcialjuego',
    storageBucket: 'parcialjuego.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-XhnK9Wq9y69TWRLvtzWnGQEI_Qbmdg',
    appId: '1:704952785545:ios:afef579fee03177fdcc458',
    messagingSenderId: '704952785545',
    projectId: 'parcialjuego',
    storageBucket: 'parcialjuego.firebasestorage.app',
    iosBundleId: 'com.example.parcialJuego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH-XhnK9Wq9y69TWRLvtzWnGQEI_Qbmdg',
    appId: '1:704952785545:ios:afef579fee03177fdcc458',
    messagingSenderId: '704952785545',
    projectId: 'parcialjuego',
    storageBucket: 'parcialjuego.firebasestorage.app',
    iosBundleId: 'com.example.parcialJuego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-UiLowxnRMnKC3IJ6Qxw61i_HsFDhpOg',
    appId: '1:704952785545:web:e0ffceeb144ae60bdcc458',
    messagingSenderId: '704952785545',
    projectId: 'parcialjuego',
    authDomain: 'parcialjuego.firebaseapp.com',
    storageBucket: 'parcialjuego.firebasestorage.app',
    measurementId: 'G-DBQQ5ZWT75',
  );
}
